version: '3.5'
services:
  app:
    build:
      context: .
      args:
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      cache_from:
        - *image
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - ENV=dev
      - FLASK_DEBUG=1
      - FLASK_APP=./server.py
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
